// <auto-generated />
using System;
using ApiRest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiRest.Migrations
{
    [DbContext(typeof(NutriTecDB))]
    partial class NutriTecDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiRest.Models.Nutricionista", b =>
                {
                    b.Property<string>("cedula")
                        .HasColumnType("text");

                    b.Property<string>("apellido1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("apellido2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("cod_barras")
                        .HasColumnType("integer");

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("edad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("foto")
                        .HasColumnType("bytea");

                    b.Property<int>("imc")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("num_tarj_credi")
                        .HasColumnType("integer");

                    b.Property<int>("peso")
                        .HasColumnType("integer");

                    b.HasKey("cedula");

                    b.ToTable("Nutricionistas");
                });
#pragma warning restore 612, 618
        }
    }
}
